# Generated by Django 4.1.7 on 2023-03-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecard',
            name='position',
            field=models.CharField(default=True, max_length=250),
            preserve_default=False,
        ),
    ]
