# Generated by Django 4.1.7 on 2023-03-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employeecard_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecard',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
