# Generated by Django 4.1.7 on 2023-03-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_employeecard_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecard',
            name='encoded_qr_qode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeecard',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
