# Generated by Django 4.1.7 on 2023-03-11 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_employeecard_encoded_qr_qode_employeecard_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecard',
            name='user',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
