# Generated by Django 4.1.7 on 2023-03-11 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_employeecard_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecard',
            name='user',
        ),
    ]
